"""
This type stub file was generated by pyright.
"""

from keras import _tf_keras as _tf_keras, activations as activations, applications as applications, backend as backend, callbacks as callbacks, config as config, constraints as constraints, datasets as datasets, distillation as distillation, distribution as distribution, dtype_policies as dtype_policies, export as export, initializers as initializers, layers as layers, legacy as legacy, losses as losses, metrics as metrics, mixed_precision as mixed_precision, models as models, ops as ops, optimizers as optimizers, preprocessing as preprocessing, quantizers as quantizers, random as random, regularizers as regularizers, saving as saving, tree as tree, utils as utils, visualization as visualization, wrappers as wrappers
from keras.src.backend import Variable as Variable, device as device, name_scope as name_scope
from keras.src.backend.common.keras_tensor import KerasTensor as KerasTensor
from keras.src.backend.common.remat import RematScope as RematScope, remat as remat
from keras.src.backend.common.stateless_scope import StatelessScope as StatelessScope
from keras.src.backend.common.symbolic_scope import SymbolicScope as SymbolicScope
from keras.src.dtype_policies.dtype_policy import DTypePolicy as DTypePolicy, FloatDTypePolicy as FloatDTypePolicy
from keras.src.initializers.initializer import Initializer as Initializer
from keras.src.layers.core.input_layer import Input as Input
from keras.src.layers.input_spec import InputSpec as InputSpec
from keras.src.layers.layer import Layer as Layer
from keras.src.losses.loss import Loss as Loss
from keras.src.metrics.metric import Metric as Metric
from keras.src.models.model import Model as Model
from keras.src.models.sequential import Sequential as Sequential
from keras.src.ops.function import Function as Function
from keras.src.ops.operation import Operation as Operation
from keras.src.optimizers.optimizer import Optimizer as Optimizer
from keras.src.quantizers.quantizers import Quantizer as Quantizer
from keras.src.regularizers.regularizers import Regularizer as Regularizer
from keras.src.version import __version__ as __version__, version as version

"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""
